### PR TITLE
Modernize the starter kit

### PR DESCRIPTION
**Pull request by harmony7**
PR suggests:

* No longer requires Webpack
* Update to js-compute 1.5.1
* fixes language spec in fastly.toml
* fixes package/repo specs in package.json
* use modern scripts setup in fastly.toml/package.json
* use modern `fastly:*` namespaced imports for fastly features
* log service version as we do in the other starter kits

### CODE REVIEW

**Comment by JakeChampion** [comment]
@harmony7 - nice work! one thing we need to do outside of this PR is turn off shiply for this project

**Comment by noopole** [comment]
> use modern fastly:* namespaced imports for fastly features

Did you manage to run it under Windows?

I couldn't compile because of the line: `import {env} from "fastly:env"`.
For ":" is not an authorized character for a file name under Windows. So the filename appears as *fastlyenv.d.t* and the module cannot be found by **tsc**.

I had to change the name accordingly in the *@fastly/js-compute/types/index.d.tsc* to make it work but it's cannot be a permament solution.

**Comment by JakeChampion** [comment]
> > use modern fastly:* namespaced imports for fastly features
> 
> Did you manage to run it under Windows?
> 
> I couldn't compile because of the line: `import {env} from "fastly:env"`.
> For ":" is not an authorized character for a file name under Windows. So the filename appears as *fastlyenv.d.t* and the module cannot be found by **tsc**.
> 
> I had to change the name accordingly in *@fastly/js-compute/types/index.d.tsc* to make it work but it's cannot be a permament solution.
> 
>  

Does nodejs on windows support `node:` prefix imports such as `import { readFile } from 'node:fs';`?

**Comment by noopole** [comment]
> Does nodejs on windows support `node:` prefix imports such as `import { readFile } from 'node:fs';`?

Yes of course.
What is not working is the file name with a `:` character. 

If you use the unicode colon `꞉` character instead (or better: any other valid character like `-` or `_`) in the _/type/*.d.ts_ filenames and file references inside _/types/index.d.ts_, then `import {env} from "fastly:env"` (with ASCII `:`) will work.

**Pull request merged**
